name: 'Verify Commit Signature'
description: 'Verifies that commits are signed with ED25519-SK or ECDSA-SK algorithm'
inputs:
  commit-sha:
    description: 'Commit SHA to verify (defaults to HEAD)'
    required: false
    default: 'HEAD'
  fail-on-unsigned:
    description: 'Fail if commit is not signed'
    required: false
    default: 'true'
  allowed-algorithms:
    description: 'Comma-separated list of allowed algorithms (ED25519-SK,ECDSA-SK)'
    required: false
    default: 'ED25519-SK,ECDSA-SK'

outputs:
  is-signed:
    description: 'Whether the commit is signed'
    value: ${{ steps.verify.outputs.is-signed }}
  algorithm:
    description: 'The signature algorithm used'
    value: ${{ steps.verify.outputs.algorithm }}
  is-allowed:
    description: 'Whether the signature uses an allowed algorithm'
    value: ${{ steps.verify.outputs.is-allowed }}

runs:
  using: 'composite'
  steps:
    - name: Verify commit signature
      id: verify
      shell: bash
      run: |
        COMMIT_SHA="${{ inputs.commit-sha }}"
        ALLOWED_ALGOS="${{ inputs.allowed-algorithms }}"
        
        # Function to check commit signature and determine algorithm
        check_commit() {
          local commit=$1
          local verify_output
          local log_output
          local key_id
          local key_fingerprint
          local algorithm=""
          local is_sk=false
          local signature_type=""
          
          # Get both verify and log output
          verify_output=$(git verify-commit "$commit" 2>&1 || true)
          log_output=$(git log --show-signature -1 "$commit" 2>&1 || echo "")
          
          # Check if commit is signed (either GPG or SSH)
          if ! echo "$verify_output" | grep -qE "Good signature|Valid" && ! echo "$log_output" | grep -qE "Good|Valid"; then
            return 1
          fi
          
          # Determine signature type: SSH or GPG
          if echo "$log_output" | grep -qE "SSH|ssh-ed25519|ecdsa-sha2"; then
            signature_type="SSH"
          elif echo "$log_output" | grep -qE "GPG|gpg|Good signature"; then
            signature_type="GPG"
          fi
          
          # Handle SSH key signatures
          if [ "$signature_type" = "SSH" ]; then
            # Extract SSH key fingerprint from log output
            # Format: "SSH Key Fingerprint: qb64Ay4dOcFceVDxo1a4wrNTtZOufTpOaQ+Qx4lLBCE"
            key_fingerprint=$(echo "$log_output" | grep -i "SSH.*Fingerprint" | sed -n 's/.*Fingerprint[^:]*:\s*\([A-Za-z0-9+/=_-]*\).*/\1/p' | head -1 || echo "")
            
            # Also try to get from verify output
            if [ -z "$key_fingerprint" ]; then
              key_fingerprint=$(echo "$verify_output" | grep -i "fingerprint" | sed -n 's/.*[Ff]ingerprint[^:]*:\s*\([A-Za-z0-9+/=_-]*\).*/\1/p' | head -1 || echo "")
            fi
            
            # Check for security key (SK) key types in the output
            # Security keys use: sk-ssh-ed25519@openssh.com or sk-ecdsa-sha2-nistp256@openssh.com
            if echo "$log_output" "$verify_output" | grep -qiE "sk-ssh-ed25519|sk-ecdsa"; then
              is_sk=true
            fi
            
            # Check key type from log output
            if echo "$log_output" "$verify_output" | grep -qiE "sk-ssh-ed25519|ssh-ed25519|ed25519"; then
              algorithm="ED25519"
              # If we found sk-ssh-ed25519, it's definitely a security key
              if echo "$log_output" "$verify_output" | grep -qi "sk-ssh-ed25519"; then
                is_sk=true
              fi
            elif echo "$log_output" "$verify_output" | grep -qiE "sk-ecdsa|ecdsa-sha2|ecdsa"; then
              algorithm="ECDSA"
              # If we found sk-ecdsa, it's definitely a security key
              if echo "$log_output" "$verify_output" | grep -qi "sk-ecdsa"; then
                is_sk=true
              fi
            fi
            
            # If we have a fingerprint but no algorithm, try to determine from fingerprint length/format
            if [ -z "$algorithm" ] && [ -n "$key_fingerprint" ]; then
              # ED25519 fingerprints are typically 43-44 base64 chars
              if [ ${#key_fingerprint} -ge 40 ] && [ ${#key_fingerprint} -le 44 ]; then
                algorithm="ED25519"
              # ECDSA fingerprints vary but are usually longer
              elif [ ${#key_fingerprint} -gt 44 ]; then
                algorithm="ECDSA"
              fi
            fi
            
            # Additional check: if the key type contains "sk-" anywhere, it's a security key
            if echo "$log_output" "$verify_output" | grep -qi "sk-"; then
              is_sk=true
            fi
          fi
          
          # Handle GPG signatures
          if [ "$signature_type" = "GPG" ] || [ -z "$signature_type" ]; then
            # Extract key ID
            key_id=$(echo "$verify_output" | grep -oP '(?<=using )\S+(?= key)' | head -1 || echo "")
            
            if [ -z "$key_id" ]; then
              key_id=$(echo "$log_output" | grep -oP '(?<=key ID )\S+' | head -1 || echo "")
            fi
            
            # Get key information
            if [ -n "$key_id" ]; then
              key_info=$(gpg --list-keys --with-colons "$key_id" 2>/dev/null || echo "")
              
              if [ -n "$key_info" ]; then
                algo_code=$(echo "$key_info" | grep "^pub:" | cut -d: -f4 || echo "")
                
                case "$algo_code" in
                  22) algorithm="ED25519" ;;
                  19|18|25) algorithm="ECDSA" ;;
                esac
                
                full_key_list=$(gpg --list-keys --with-keygrip "$key_id" 2>/dev/null || echo "")
                
                if echo "$full_key_list" | grep -qiE "\[.*S.*\]|card|security|yubikey|sk"; then
                  is_sk=true
                fi
                
                if echo "$verify_output" | grep -qiE "card|security|yubikey|sk"; then
                  is_sk=true
                fi
              fi
            fi
            
            # Fallback: check log/verify output for algorithm mentions
            if [ -z "$algorithm" ]; then
              if echo "$log_output" "$verify_output" | grep -qi "ed25519"; then
                algorithm="ED25519"
                if echo "$log_output" "$verify_output" | grep -qiE "sk|card|security|yubikey"; then
                  is_sk=true
                fi
              elif echo "$log_output" "$verify_output" | grep -qi "ecdsa"; then
                algorithm="ECDSA"
                if echo "$log_output" "$verify_output" | grep -qiE "sk|card|security|yubikey"; then
                  is_sk=true
                fi
              fi
            fi
          fi
          
          # Add SK suffix if it's a security key
          if [ "$is_sk" = true ] && [ -n "$algorithm" ]; then
            algorithm="${algorithm}-SK"
          fi
          
          # Return algorithm or empty if not found
          if [ -n "$algorithm" ]; then
            echo "$algorithm"
            return 0
          else
            return 1
          fi
        }
        
        # Verify the commit
        ALGORITHM=$(check_commit "$COMMIT_SHA" 2>&1)
        CHECK_EXIT=$?
        
        if [ $CHECK_EXIT -ne 0 ] || [ -z "$ALGORITHM" ]; then
          echo "is-signed=false" >> $GITHUB_OUTPUT
          echo "algorithm=" >> $GITHUB_OUTPUT
          echo "is-allowed=false" >> $GITHUB_OUTPUT
          
          if [ "${{ inputs.fail-on-unsigned }}" == "true" ]; then
            echo "❌ Commit $COMMIT_SHA is not signed or signature could not be verified"
            exit 1
          else
            echo "⚠️  Commit $COMMIT_SHA is not signed (non-fatal)"
            exit 0
          fi
        fi
        
        # Check if algorithm is in allowed list
        IS_ALLOWED="false"
        IFS=',' read -ra ALGO_ARRAY <<< "$ALLOWED_ALGOS"
        for algo in "${ALGO_ARRAY[@]}"; do
          algo_trimmed=$(echo "$algo" | xargs)
          if [ "$ALGORITHM" == "$algo_trimmed" ]; then
            IS_ALLOWED="true"
            break
          fi
        done
        
        echo "is-signed=true" >> $GITHUB_OUTPUT
        echo "algorithm=$ALGORITHM" >> $GITHUB_OUTPUT
        echo "is-allowed=$IS_ALLOWED" >> $GITHUB_OUTPUT
        
        if [ "$IS_ALLOWED" = "false" ]; then
          echo "❌ Commit $COMMIT_SHA is signed with algorithm '$ALGORITHM', but only $ALLOWED_ALGOS are allowed"
          exit 1
        fi
        
        echo "✅ Commit $COMMIT_SHA is signed with allowed algorithm: $ALGORITHM"

    - name: Verify all commits in PR/push
      if: github.event_name == 'pull_request' || github.event_name == 'push'
      shell: bash
      run: |
        # Function to check commit (same as above)
        check_commit() {
          local commit=$1
          local verify_output
          local log_output
          local key_id
          local key_fingerprint
          local algorithm=""
          local is_sk=false
          local signature_type=""
          
          verify_output=$(git verify-commit "$commit" 2>&1 || true)
          log_output=$(git log --show-signature -1 "$commit" 2>&1 || echo "")
          
          if ! echo "$verify_output" | grep -qE "Good signature|Valid" && ! echo "$log_output" | grep -qE "Good|Valid"; then
            return 1
          fi
          
          if echo "$log_output" | grep -qE "SSH|ssh-ed25519|ecdsa-sha2"; then
            signature_type="SSH"
          elif echo "$log_output" | grep -qE "GPG|gpg|Good signature"; then
            signature_type="GPG"
          fi
          
          if [ "$signature_type" = "SSH" ]; then
            key_fingerprint=$(echo "$log_output" | grep -i "SSH.*Fingerprint" | sed -n 's/.*Fingerprint[^:]*:\s*\([A-Za-z0-9+/=_-]*\).*/\1/p' | head -1 || echo "")
            
            if [ -z "$key_fingerprint" ]; then
              key_fingerprint=$(echo "$verify_output" | grep -i "fingerprint" | sed -n 's/.*[Ff]ingerprint[^:]*:\s*\([A-Za-z0-9+/=_-]*\).*/\1/p' | head -1 || echo "")
            fi
            
            # Check for security key (SK) key types
            if echo "$log_output" "$verify_output" | grep -qiE "sk-ssh-ed25519|sk-ecdsa"; then
              is_sk=true
            fi
            
            if echo "$log_output" "$verify_output" | grep -qiE "sk-ssh-ed25519|ssh-ed25519|ed25519"; then
              algorithm="ED25519"
              if echo "$log_output" "$verify_output" | grep -qi "sk-ssh-ed25519"; then
                is_sk=true
              fi
            elif echo "$log_output" "$verify_output" | grep -qiE "sk-ecdsa|ecdsa-sha2|ecdsa"; then
              algorithm="ECDSA"
              if echo "$log_output" "$verify_output" | grep -qi "sk-ecdsa"; then
                is_sk=true
              fi
            fi
            
            if [ -z "$algorithm" ] && [ -n "$key_fingerprint" ]; then
              if [ ${#key_fingerprint} -ge 40 ] && [ ${#key_fingerprint} -le 44 ]; then
                algorithm="ED25519"
              elif [ ${#key_fingerprint} -gt 44 ]; then
                algorithm="ECDSA"
              fi
            fi
            
            # Additional check: if the key type contains "sk-", it's a security key
            if echo "$log_output" "$verify_output" | grep -qi "sk-"; then
              is_sk=true
            fi
          fi
          
          if [ "$signature_type" = "GPG" ] || [ -z "$signature_type" ]; then
            key_id=$(echo "$verify_output" | grep -oP '(?<=using )\S+(?= key)' | head -1 || echo "")
            
            if [ -z "$key_id" ]; then
              key_id=$(echo "$log_output" | grep -oP '(?<=key ID )\S+' | head -1 || echo "")
            fi
            
            if [ -n "$key_id" ]; then
              key_info=$(gpg --list-keys --with-colons "$key_id" 2>/dev/null || echo "")
              
              if [ -n "$key_info" ]; then
                algo_code=$(echo "$key_info" | grep "^pub:" | cut -d: -f4 || echo "")
                
                case "$algo_code" in
                  22) algorithm="ED25519" ;;
                  19|18|25) algorithm="ECDSA" ;;
                esac
                
                full_key_list=$(gpg --list-keys --with-keygrip "$key_id" 2>/dev/null || echo "")
                
                if echo "$full_key_list" | grep -qiE "\[.*S.*\]|card|security|yubikey|sk"; then
                  is_sk=true
                fi
                
                if echo "$verify_output" | grep -qiE "card|security|yubikey|sk"; then
                  is_sk=true
                fi
              fi
            fi
            
            if [ -z "$algorithm" ]; then
              if echo "$log_output" "$verify_output" | grep -qi "ed25519"; then
                algorithm="ED25519"
                if echo "$log_output" "$verify_output" | grep -qiE "sk|card|security|yubikey"; then
                  is_sk=true
                fi
              elif echo "$log_output" "$verify_output" | grep -qi "ecdsa"; then
                algorithm="ECDSA"
                if echo "$log_output" "$verify_output" | grep -qiE "sk|card|security|yubikey"; then
                  is_sk=true
                fi
              fi
            fi
          fi
          
          if [ "$is_sk" = true ] && [ -n "$algorithm" ]; then
            algorithm="${algorithm}-SK"
          fi
          
          if [ -n "$algorithm" ]; then
            echo "$algorithm"
            return 0
          else
            return 1
          fi
        }
        
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          BASE_SHA="${{ github.event.pull_request.base.sha }}"
          HEAD_SHA="${{ github.event.pull_request.head.sha }}"
        else
          BASE_SHA="${{ github.event.before }}"
          HEAD_SHA="${{ github.event.after }}"
        fi
        
        # Get list of commits to verify
        if [ "$BASE_SHA" != "0000000000000000000000000000000000000000" ] && [ -n "$BASE_SHA" ]; then
          COMMITS=$(git rev-list --no-merges "$BASE_SHA..$HEAD_SHA" 2>/dev/null || echo "")
        else
          COMMITS="$HEAD_SHA"
        fi
        
        if [ -z "$COMMITS" ]; then
          echo "No commits to verify"
          exit 0
        fi
        
        FAILED=0
        ALLOWED_ALGOS="${{ inputs.allowed-algorithms }}"
        
        for COMMIT in $COMMITS; do
          echo "Checking commit $COMMIT..."
          
          ALGORITHM=$(check_commit "$COMMIT" 2>&1)
          CHECK_EXIT=$?
          
          if [ $CHECK_EXIT -ne 0 ] || [ -z "$ALGORITHM" ]; then
            echo "❌ Commit $COMMIT is not signed or signature could not be verified"
            FAILED=1
            continue
          fi
          
          IS_ALLOWED="false"
          IFS=',' read -ra ALGO_ARRAY <<< "$ALLOWED_ALGOS"
          for algo in "${ALGO_ARRAY[@]}"; do
            algo_trimmed=$(echo "$algo" | xargs)
            if [ "$ALGORITHM" == "$algo_trimmed" ]; then
              IS_ALLOWED="true"
              break
            fi
          done
          
          if [ "$IS_ALLOWED" = "false" ]; then
            echo "❌ Commit $COMMIT is signed with algorithm '$ALGORITHM', but only $ALLOWED_ALGOS are allowed"
            FAILED=1
          else
            echo "✅ Commit $COMMIT is signed with allowed algorithm: $ALGORITHM"
          fi
        done
        
        if [ $FAILED -eq 1 ]; then
          exit 1
        fi
