name: 'Verify Commit Signature'
description: 'Verifies that commits are signed with ED25519-SK or ECDSA-SK algorithm (SSH) or records GPG fingerprints'
inputs:
  commit-sha:
    description: 'Commit SHA to verify (defaults to HEAD)'
    required: false
    default: 'HEAD'
  fail-on-unsigned:
    description: 'Fail if a commit is not signed'
    required: false
    default: 'true'
  allowed-algorithms:
    description: 'Comma-separated list of allowed SSH signature algorithms (default: ED25519-SK,ECDSA-SK)'
    required: false
    default: 'ED25519-SK,ECDSA-SK'
  gpg-allowed-fingerprints:
    description: 'Comma/newline-separated list of allowed GPG fingerprints (leave blank to accept any)'
    required: false
    default: ''
  gpg-allowed-fingerprints-file:
    description: 'Path to a file containing newline-separated GPG fingerprints (combined with inline list)'
    required: false
    default: ''
  ssh-allowed-signers:
    description: 'Contents of an allowed_signers file used for ssh signature verification (principal public-key pairs)'
    required: false
    default: ''
  ssh-allowed-signers-file:
    description: 'Path to an allowed_signers file checked into the repo (overrides ssh-allowed-signers)'
    required: false
    default: ''

outputs:
  is-signed:
    description: 'Whether the requested commit is signed'
    value: ${{ steps.verify_single.outputs.is-signed }}
  algorithm:
    description: 'The signature algorithm detected for the requested commit'
    value: ${{ steps.verify_single.outputs.algorithm }}
  is-allowed:
    description: 'Whether the signature algorithm is allowed (SSH signatures only)'
    value: ${{ steps.verify_single.outputs.is-allowed }}
  fingerprint:
    description: 'Detected fingerprint (SSH key fingerprint or GPG fingerprint)'
    value: ${{ steps.verify_single.outputs.fingerprint }}

runs:
  using: 'composite'
  steps:
    - name: Verify requested commit
      id: verify_single
      shell: bash
      run: |
        set -euo pipefail
        python3 .github/actions/verify-commit-signature/verify_commits.py single
      env:
        INPUT_COMMIT_SHA: ${{ inputs.commit-sha }}
        INPUT_ALLOWED_ALGORITHMS: ${{ inputs.allowed-algorithms }}
        INPUT_GPG_ALLOWED_FINGERPRINTS: ${{ inputs.gpg-allowed-fingerprints }}
        INPUT_FAIL_ON_UNSIGNED: ${{ inputs.fail-on-unsigned }}
        INPUT_SSH_ALLOWED_SIGNERS: ${{ inputs.ssh-allowed-signers }}
        INPUT_SSH_ALLOWED_SIGNERS_FILE: ${{ inputs.ssh-allowed-signers-file }}
        INPUT_GPG_ALLOWED_FINGERPRINTS_FILE: ${{ inputs.gpg-allowed-fingerprints-file }}

    - name: Verify commits in pull request
      if: github.event_name == 'pull_request'
      shell: bash
      run: |
        set -euo pipefail
        python3 .github/actions/verify-commit-signature/verify_commits.py range
      env:
        INPUT_ALLOWED_ALGORITHMS: ${{ inputs.allowed-algorithms }}
        INPUT_GPG_ALLOWED_FINGERPRINTS: ${{ inputs.gpg-allowed-fingerprints }}
        INPUT_FAIL_ON_UNSIGNED: ${{ inputs.fail-on-unsigned }}
        INPUT_SSH_ALLOWED_SIGNERS: ${{ inputs.ssh-allowed-signers }}
        INPUT_SSH_ALLOWED_SIGNERS_FILE: ${{ inputs.ssh-allowed-signers-file }}
        INPUT_BASE_SHA: ${{ github.event.pull_request.base.sha }}
        INPUT_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        INPUT_GPG_ALLOWED_FINGERPRINTS_FILE: ${{ inputs.gpg-allowed-fingerprints-file }}

    - name: Verify commits in push
      if: github.event_name == 'push'
      shell: bash
      run: |
        set -euo pipefail
        python3 .github/actions/verify-commit-signature/verify_commits.py range
      env:
        INPUT_ALLOWED_ALGORITHMS: ${{ inputs.allowed-algorithms }}
        INPUT_GPG_ALLOWED_FINGERPRINTS: ${{ inputs.gpg-allowed-fingerprints }}
        INPUT_FAIL_ON_UNSIGNED: ${{ inputs.fail-on-unsigned }}
        INPUT_SSH_ALLOWED_SIGNERS: ${{ inputs.ssh-allowed-signers }}
        INPUT_SSH_ALLOWED_SIGNERS_FILE: ${{ inputs.ssh-allowed-signers-file }}
        INPUT_BASE_SHA: ${{ github.event.before }}
        INPUT_HEAD_SHA: ${{ github.event.after }}
        INPUT_GPG_ALLOWED_FINGERPRINTS_FILE: ${{ inputs.gpg-allowed-fingerprints-file }}
